### PR TITLE
feat: added configuration default fill color and default stroke color

### PR DESCRIPTION
**Pull request by zxuanhong**
1. Added configuration default fill color and default stroke color.This makes some special environment display better(such as dark mode).This configuration is consistent with bpmn js
2. Adjust the color svg icon stroke-width to equal 2 so that the border color is clearer
iShot_2023-05-25_15 55 38
iShot_2023-05-25_15 55 15

### CODE REVIEW

**Comment by smbea** [comment]
> Adjust the color svg icon stroke-width to equal 2 so that the border color is clearer

I'm not sure we want to change the stroke. We've had some discussions on the UI of the color picker but I don't remember if this was an issue that was discussed @nikku

**Comment by nikku** [comment]
@zxuanhong Could you tell us why we don't simply set this to the default fill and stroke color provided by bpmn-js? Why would we want to set this extra?

**Comment by zxuanhong** [comment]
@nikku In Dark mode, the color without fill or stroke should follow bpmn js in Dark mode.Or this will result in a color mismatch with bpmn js(bpmn js changes the default color situation).That is, bpmn js does the following
image

**Comment by nikku** [comment]
Exactly. This is why I'm asking:

* Why make it possible to configure an extra color, when alternatively we can read the default color configured with bpmn-js and use that?

**Comment by zxuanhong** [comment]
@nikku I haven't tried to read it, but the idea is perfect. I'll update it later

**Comment by zxuanhong** [comment]
In Dark mode, the color without fill or stroke should follow bpmn js in Dark mode



---- Replied Message ----
| From | Nico ***@***.***> |
| Date | 05/25/2023 21:32 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [bpmn-io/bpmn-js-color-picker] feat: added configuration default fill color and default stroke color (PR #26) |

@zxuanhong Could you tell us why we don't simply set this to the default fill and stroke color provided by bpmn-js? Why would we want to set this extra?

**Comment by zxuanhong** [comment]
@nikku Thanks again for your guidance

**Comment by nikku** [comment]
Released with v0.6.0.

**Pull request merged**
